/*
    layout.tsx
    ＜概要＞
        アプリ全体のレイアウト指定。
          アプリ画面：上部にトップバー、他はメイン領域
        どこからでもプルダウンメニューとタイトルを変更できるよう設定。
        トップバー表示。
    ＜使い方＞
        自動で呼び出されるため使い方は不要。
*/

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import React from "react";
import { TopBar } from "@/components/TopBar";
import { SubBar } from "@/components/SubBar";
import { BottomBar } from "@/components/BottomBar";
import { Layout } from "@/components/Layout";
import { AppProvider } from "@/components/AppProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Oshinagaki",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <div className=" h-[100svh] //高さがスクリーン全体 flex flex-col " >
            <TopBar /> {/* トップバー表示 */}
            <SubBar /> {/* サブバー表示 */}
            <Layout>
              {children}
            </Layout>
            <BottomBar /> {/* ボトムバー表示 */}
          </div>
        </AppProvider>
      </body>
    </html >
  );
}